#!/usr/bin/python3.6
# -*- coding: utf-8 -*-
# Names module

from random import *
from util import *

class Names:
	def __init__(self):
		self._FirstNamesList = WordList()
		self._LastNamesList = WordList()
		
	def FirstName(self, NotList = None):
		if NotList is None:
			NotList = []
			
		return self._FirstNamesList.GetWord(NotList = NotList)
		
	def SetFirstNames(self, NewList = None):
		if NewList is None:
			NewList = []
			
		self._FirstNamesList = WordList(NewList)
		
	def GetFirstNamesList(self):
		return self._FirstNamesList.List 
	
	def LastName(self, NotList = None):
		if NotList is None:
			NotList = []
	
		return self._LastNamesList.GetWord(NotList = NotList)
		
	def SetLastNames(self, NewList = None):
		if NewList is None:
			NewList = []
			
		self._LastNamesList = WordList(NewList)
		
	def GetLastNamesList(self):
		return self._LastNamesList.List 
		
class ClassyNamesFemale(Names):
	def __init__(self):
		super().__init__()
		self.SetFirstNames(['Alana',
			'Alexis',
			'Amelia',
			'Anastasia',
			'Angela',
			'Angelica',
			'Anita',
			'Annabel',
			'Aria',
			'Autumn',
			'Ava',
			'Bella',
			'Belle',
			'Bianca',
			'Brielle',
			'Brigitte',
			'Brynn',
			'Calliope',
			'Candy',
			'Caroline',
			'Carmina',
			'Cecie',
			'Charity',
			'Chelsea',
			'Clarissa',
			'Colette',
			'Constance',
			'Cordelia',
			'Daisy',
			'Dalia',
			'Dani',
			'Dannielle',
			'Daphne',
			'Deanna',
			'Delilah',
			'Delores',
			'Eden',
			'Eliza',
			'Elspeth',
			'Esmerelda',
			'Estelle',
			'Felicia',
			'Felicity',
			'Fiona',
			'Florence',
			'Francesca',
			'Georgina',
			'Gisele',
			'Harmony',
			'Heidi',
			'Heaven',
			'Honey',
			'Indigo',
			'Isabelle',
			'Jacinda',
			'Jaqueline',
			'Jasmine',
			'Josephine',
			'Juliana',
			'Juliette',
			'Juniper',
			'Jynx',
			'Kaitlyn',
			'Katrina',
			'Lacey',
			'Laurel',
			'Lauren',
			'Lavinia',
			'Lelani',
			'Leslie',
			'Lilah',
			'Lilli',
			'Lola',
			'Marianna',
			'Marilyn',
			'Melina',
			'Molly',
			'Morgan',
			'Natasha',
			'Olive',
			'Olivia',
			'Ophelia',
			'Paris',
			'Penelope',
			'Phoebe',
			'Piper',
			'Raven',
			'Regina',
			'Rhonda',
			'Roanna',
			'Rosaline',
			'Roxanne',
			'Ruby',
			'Sable',
			'Sabrina',
			'Saffron',
			'Satin',
			'Savannah',
			'Scarlett',
			'Simone',
			'Sophie',
			'Summer',
			'Svetlana',
			'Sydney',
			'Sylvia',
			'Tonya',
			'Tori',
			'Valentina',
			'Vanessa',
			'Veronica',
			'Viola',
			'Violet',
			'Virginia',
			'Vivienne'])
			
class PlainNamesFemale(Names):
	def __init__(self):
		super().__init__()
		self.SetFirstNames(['Amber',
							   'Anne',
							   'Annie',
							   'Cindy',
							   'Beatrice',
							   'Betty',
							   'Dianne',
							   'Donna',
							   'Doris',
							   'Elizabeth',
							   'Emma',
							   'Ericka',
							   'Ginger',
							   'Harriet',
							   'Holly',
							   'Jane',
							   'June',
							   'Lucy',
							   'Kim',
							   'Kitty',
							   'Lilly',
							   'Marsha',
							   'Mary',
							   'Mary Jane',
							   'May',
							   'Mel',
							   'Melissa',
							   'Misty',
							   'Rachael',
							   'Sally',
							   'Tasha',
							   'Tess',
							   'Tiffany',
							   'Vicky',
							   ])
							   
class InnuendoNamesFemale(Names):
	def __init__(self):
		super().__init__()
		
		self.SetFirstNames(['Amanda','Amanda','Amanda',
							'Anita','Anita','Anita','Anita',
							'Anna',
							'Candy',
							'Carrie',
							'Chastity',
							'Cherry','Cherry',
							'Deepa',
							'Dixie',
							'Eden','Eden','Eden',
							'Fonda','Fonda',
							'Hilda',
							'Honey',
							'Ida',
							'Ima',
							'Inya','Inya',
							'Issa','Issa',
							'Ivana','Ivana','Ivana','Ivana',
							'Jackie',
							'Jill',
							'Juanita',
							'Kari',
							'Maya',
							'Misty',
							'Muffy',
							'Nastya',
							#'Nell',
							'Olive',
							'Olivia','Olivia',
							'Ophelia','Ophelia','Ophelia',
							'Rhoda','Rhoda','Rhoda','Rhoda',
							'Rosie',
							'Sandy',
							'Satin',
							'Sharon','Sharon','Sharon',
							'Tara',
							'Tina',
							'Tonya',
							'Wilma'])
			
class NamesFemale(Names):
	def __init__(self):
		super().__init__()
		
		self.SetFirstNames(ClassyNamesFemale().GetFirstNamesList())
		
class AuthorNamesFemale(Names):
	def __init__(self):
		super().__init__()
		
		self.SetFirstNames(ClassyNamesFemale().GetFirstNamesList() + InnuendoNamesFemale().GetFirstNamesList())

class PlainNamesMale(Names):
	def __init__(self):
		super().__init__()
		
		self.SetFirstNames(['Allen',
							   'Ben',
							   'Bob',
							   'Chuck',
							   'Dan',
							   'Dick',
							   'Doug',
							   'Duane',
							   'Earl',
							   'Ed',
							   'Frank',
							   'Greg',
							   'Hank',
							   'Harry',
							   'Isaac',
							   'Ivan',
							   'James',
							   'Jeff',
							   'Jim',
							   'Jimmy',
							   'Joe',
							   'John',
							   'Josh',
							   'Kenny',
							   'Lenny',
							   'Lou',
							   'Mike',
							   'Nick',
							   'Phil',
							   'Philip',
							   'Rob',
							   'Rusty',
							   'Steve',
							   'Steven',
							   'Ted',
							   'Tim',
							   'Tom',
							   'Will',
							   'Zach',
							   'Zeke'])

class ClassyNamesMale(Names):
	def __init__(self):
		super().__init__()
		
		self.SetFirstNames(['Adam',
			'Alistair',
			'Ambrose',
			'Andre',
			'Angel',
			'Apollo',
			'Archer',
			'Blake',
			'Brad',
			'Bradford',
			'Bradley',
			'Cal',
			'Chad',
			'Christopher',
			'Clint',
			'Clive',
			'Connor',
			'Cullen',
			'Dallas',
			'Dante',
			'Darius',
			'Deacon',
			'Desmond',
			'Dominic',
			'Drake',
			'Duke',
			'Eduardo',
			'Esteban',
			'Ferdinand',
			'Finn',
			'Flint',
			'Gavin',
			'Geoffrey',
			'Grant',
			'Griffin',
			'Grigory',
			'Hudson',
			'Hunter',
			'Iain',
			'Ivan',
			'Javier',
			'Jordan',
			'Juan',
			'Julian',
			'Kane',
			'Leo',
			'Leon',
			'Lex',
			'Liam',
			'Lorenzo',
			'Manuel',
			'Marco',
			'Max',
			'Michael',
			'Miles',
			'Nicolas',
			'Pablo',
			'Peter',
			'Quentin',
			'Quinn',
			'Rafael',
			'Rafe',
			'Ramon',
			'Raoul',
			'Reed',
			'Reginald',
			'Remington',
			'Rex',
			'Ricardo',
			'Richard',
			'Rico',
			'Roberto',
			'Rogan',
			'Roland',
			'Romeo',
			'Ronson',
			'Rowan',
			'Royce',
			'Ruben',
			'Russell',
			'Ryder',
			'Sean',
			'Sebastian',
			'Sergei',
			'Shane',
			'Stefan',
			'Sterling',
			'Tremaine',
			'Trey',
			'Tristan',
			'Tristan',
			'Tucker',
			'Ty',
			'Vance',
			'Vaughan',
			'Vicenzo',
			'Vincent',
			'Xavier'])
	   
class InnuendoNamesMale(Names):
	def __init__(self):
		super().__init__()
		
		self.SetFirstNames(['Barry',
			'Ben','Ben',
			'Buster',
			'Dewey','Dewey',
			'Dick','Dick','Dick',
			'Dirk',
			'Dixon',
			'Gaylord',
			'Hans',
			'Harry','Harry','Harry',
			'Holden','Holden',
			'Howie',
			'Hugh','Hugh',
			'Jack','Jack',
			'Juan',
			'Kanye',
			'Lance','Lance',
			'Major',
			'Max',
			#'Mike','Mike',
			'Neil',
			'Oliver','Oliver',
			'Otto',
			'Pat','Pat',
			'Peter','Peter',
			'Phil',
			'Philip',
			'Philmore',
			'Randy',
			'Rich','Rich',
			'Rod',
			'Ryder',
			'Sawyer','Sawyer',
			'Seymour','Seymour','Seymour',
			'Willie','Willie',
			'Woody','Woody'
			])
			
class AuthorNamesMale(Names):
	def __init__(self):
		super().__init__()
		
		self.SetFirstNames(InnuendoNamesMale().GetFirstNamesList() + ClassyNamesMale().GetFirstNamesList())
		
class DiverseNamesMale(Names):
	def __init__(self):
		super().__init__()
		
		self.SetFirstNames(ClassyNamesMale().GetFirstNamesList() + PlainNamesMale().GetFirstNamesList())		
		
class NamesMale(Names):
	def __init__(self):
		super().__init__()
		
		self.SetFirstNames(ClassyNamesMale().GetFirstNamesList())
			
class InnuendoLastNames(WordList):
	def __init__(self):
		super().__init__()
		
		self.List = ["Amalova",
			"Analiquor",
			"Anlicker",
			"Bangs","Bangs",
			"Bear",
			"Beaver","Beaver","Beaver",
			"Beeter",
			"Bendz",
			"Biggs",
			"Blower",
			"Blush",
			"Bodie",
			"Brest","Bresst",
			"Broad",
			"Brownie",
			"Bottoms",
			"Buhnz",
			"Butts",
			"Cherry",
			"Clam",
			"Clams",
			"Clozov",
			"Cox",
			"Cracks",
			"Cream",
			"Creamer",
			"Creams",
			"Cummer",
			"Cummings","Cummings",
			"Daley",
			"Dick",
			"Dickens",
			"Dicker",
			"Dicter",
			"Dix",
			"Djerkov",
			"Djiz",
			"Fatt",
			"Faulks",
			"Felch",
			"Feltcher",
			"Fuchs",
			"Furrows",
			"Galey",
			"Gaylord",
			"Goodebody",
			"Goodhead",
			"Gozinya",
			"Grotch",
			"Hancock",
			"Handler",
			"Hard",
			"Harder",
			"Hardin",
			"Head",
			"Hiscock",
			"Ho","Ho","Ho",
			"Hoar",
			"Holden",
			"Holston",
			"Hump",
			"Humper",
			"Hung","Hung",
			#"Hunt",
			"Hyman",
			"Hunter",
			"Inya",
			"Janus",
			"Jacov",
			"Jiggles",
			"Johnson","Johnson",
			"Knightly",
			"Knockers",
			"Knott",
			"Knuttz",
			"Koch",
			"Kootch",
			"Krevises",
			"Kuntz",
			"Lipps",
			"Liquor",
			"Lode",
			"Long",
			"Lust",
			"Mann",
			"McCreviss",
			"Mehoff",
			"Mellck",
			"Milfinger",
			"Minx",
			"Moon",
			"Moore",
			"Moorecox",
			"Moorehard",
			"Moorehead",
			"Mortits",
			"Mount",
			"Mountcox",
			"Mountford",
			"Muncher",
			"Muff",
			"Muffin",
			"Nippell",
			"Oxhard",
			"Peach",
			"Peaches",
			"Pearl",
			"Pecker",
			"Peckwood",
			"Peters","Peters",
			"Philmore",
			"Pink",
			"Pohl",
			"Polk",
			"Poppa",
			"Puss",
			"Popper",
			"Posey",
			"Pu",
			"Rack",
			"Rohdd",
			"Rimmer",
			"Rubber",
			"Sachs",
			"Sacks",
			"Sax",
			"Schaft",
			"Schlong",
			"Snatch",
			"Spreader",
			"Spunck",
			"Stiffington",
			"Stiffly",
			"Stiffy",
			"Stinker",
			"Stroker",
			"Stuffers",
			"Swallower",
			"Swallows",
			"Throat",
			"Topper",
			"Wang",
			"Weiner",
			"Wood",
			"Zemen"]
			
class ClassyLastNames(WordList):
	def __init__(self):
		super().__init__()
		
		self.List = ["Bardot",
					"Black",
					"Church",
					"Cho",
					"De Boest",
					"Devlyn",
					"Fox",
					"Hu",
					"Johnson",
					"Jones",
					"King",
					"Knight",
					"Knox",
					"Lace",
					"La Vigne",
					"Mandelay",
					"Morgan",
					"Prince",
					"Quinn",
					"Red",
					"Rose",
					"St. Claire",
					"St. Thomas",
					"Steele",
					"Strange",
					"Sweet",
					"Vale",
					"Valentine",
					"White",
					"Wilde",
					"Winters",
					"Zahara"]
			
class PlainLastNames(WordList):
	def __init__(self):
		super().__init__()
		
		self.List = ['Beaver',
					  'Bell',
					  'Bottoms',
					  'Brown',
					  'Butts',
					  'Chang',
					  'Chin',
					  'Church',
					  'Clark',
					  'Cox',
					  'Cummings',
					  'Davis',
					  'Goodbody',
					  'Gonzalez',
					  'Gray',
					  'Green',
					  'Hancock',
					  'Hill',
					  'Jefferson',
					  'Johnson',
					  'Jones',
					  'King',
					  'Lee',
					  'Long',
					  'Lopez',
					  'Moore',
					  'Moorecox',
					  'Pearl',
					  'Peters',
					  'Philmore',
					  'Robinson',
					  'Rogers',
					  'Ross',
					  'Sanderson',
					  'Smith',
					  'Taylor',
					  'Wang',
					  'White',
					  'Williams',
					  'Wilson',
					  'Wood'
					]
					
class AuthorLastNames(WordList):
	def __init__(self):
		super().__init__()
		
		self.List = InnuendoLastNames().List + ClassyLastNames().List
		
class RegularLastNames(WordList):
	def __init__(self):
		super().__init__()
		
		self.List = PlainLastNames().List + ClassyLastNames().List